# Generated by Django 5.0.6 on 2024-07-31 17:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=20)),
                ('publish_date', models.DateField(default=datetime.date(2024, 7, 31))),
            ],
        ),
    ]
